package com.nicko.XFiles.Entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity // This annotation declares the class as an entity (Basically represents a table of a db). Each instance of this entity represents a row of the corresponding table, and the attributes of this class (entity) represent the columns
public class Agent {
    @Id // This sets the ID as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // And this specifies how the PK should be generated, in this case it indicates that the PK should automatically be generated by the underlying DB
    private Long id;
    private String name;

    public Agent(String name) {
        this.name = name;
    }
}
